### PR TITLE
Sassify css components

### PR DESCRIPTION
**Pull request by xvilo**
This is the first step to more component based styles setup (https://github.com/brandly/irc/issues/41). We obviously should make it more clear and use variables more. I also included an example theme file. My idea is to just set the theme name on the body and then let it override all specific colors etc.

### CODE REVIEW

**Comment by xvilo** [comment]
Oh, and on another note, the app will use system fonts by default (like Github does). This means we have to tweak the letter spacing a bit more in future styling!

**Comment by brandly** [comment]
> My idea is to just set the theme name on the body and then let it override all specific colors etc.

i think this is a good approach. i also considered using `styled-components` at one point and implementing themes via JS variables, but i don't have strong feelings about these things.

potentially, instead of segregating the SASS files, we could have component-specific styles sitting next to the component. for example, `ChannelName.js` could become

```
ChannelName/
    index.js
    style.sass
```

maybe it's more work to set up the build scripts in this fashion, so i don't mind if we keep styles segregated for now.

i saw there's a `reset` and a `normalize` stylesheet. maybe `normalize` isn't necessary, since we're only running this on electron (but maybe it has some benefit that i don't know about)

> Oh, and on another note, the app will use system fonts by default (like Github does).

i fully support this. this repo was created a few years ago, and it's showing its age a bit :D

**Comment by xvilo** [comment]
@brandly In its current state it's not workable. That's why I did it this way, just split up the all the css you had now, from there we can work to a better solution. We have it already now in a component style, so, switching in the future wouldn't hurt too much. 

I wanted to propose to switch to TypeScript and WebPack. This way we could create 1 web pack bundle with all its assets. But that could be something for the future. 

If this PR is good for you, let's merge it and I could continue to write a first small theme :)

**Comment by brandly** [comment]
> I wanted to propose to switch to TypeScript and WebPack. 

i've liked Flow, but TypeScript seems to have better tooling surrounding it. i've only used TypeScript with [Parcel](https://parceljs.org/) which made things super easy to set up. i can look more into this stuff, but some kind of bundler could definitely improve our workflow with these components.

Parcel seems pretty impressive, if you haven't checked it out. potentially it could help us bundle SASS without having to convert everything to TypeScript (just so we're focused on the main goal and not creating too much work for ourselves)

> If this PR is good for you, let's merge it and I could continue to write a first small theme :)

let me pull this down and check it out before merging. i'm at work right now, but i'll probably have time in a few hours. i noticed your other PR which appears to build off this, so i'll try to help coordinate and get things properly merged.

thanks again ✌️

**Comment by xvilo** [comment]
> potentially it could help us bundle SASS without having to convert everything to TypeScript

That is not a requirement, we can use plain JS next to typescript! But I would recommend using it an early stage so we can easily grow the application :)

**Comment by brandly** [comment]
we already have [a type system](https://flow.org/en/), so it's probably not too hard to convert. most of the types are [defined here](https://github.com/brandly/irc/blob/master/src/js/flow/index.js).

the main struggle was trying to make redux type safe. i got things _working_, but instead of somehow deriving the type of our state tree, it's defined here:

https://github.com/brandly/irc/blob/1fc928b8d588904c5a823ff7b48b02555a4a2a9c/src/js/flow/index.js#L78-L86

ideally it would somehow be derived from this

https://github.com/brandly/irc/blob/1fc928b8d588904c5a823ff7b48b02555a4a2a9c/src/js/reducers/index.js#L8-L14

right now, if you change one of those reducer type signatures, you have to keep them in sync with the `IrcState` type. the compiler wouldn't catch it, and i'd hit some runtime errors.

what do you know about this stuff? is there a cleaner way to handle redux with TypeScript?

**Comment by brandly** [comment]
found time to merge!

i squashed the commits which might cause some trouble on that other PR (but a rebase should smooth things out, i think)

feel free to open issues for typescript/webpack, so we don't lose this discussion.

thanks again

**Pull request merged**
